name: Flaky Test CI

on:
  push:
    branches:
      - byte-buddy  
  pull_request:
    branches:
      - byte-buddy  

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11  # Change this to the Java version your project requires

      - name: Install Maven
        run: |
          sudo apt-get install maven
        shell: bash

      - name: Build and run the test
        run: |
          mvn clean install -DskipTests -pl byte-buddy-dep -am
          mvn -pl byte-buddy-dep test -Dtest=net.bytebuddy.pool.TypePoolDefaultMethodDescriptionTest#testExceptions
        shell: bash
